version: '3'

services:
  api-gympass-pg:
    image: bitnamilegacy/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker 
      - POSTGRESQL_PASSWORD=docker 
      - POSTGRESQL_DATABASE=apigympass 